name: energy-trans-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openjdk=17
  - pyspark
  - jupyterlab
  - pip
  - pip:
      - requests
      - PyYAML
      - openpyxl
      - xlrd>=2.0.1
