name: energy-trans-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openjdk=17
  - pyspark
  - jupyterlab
  - pip
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - idna==3.11
      - PyYAML==6.0.3
      - requests==2.32.5
      - urllib3==2.6.2
      - openpyxl
      - xlrd>=2.0.1
